### PR TITLE
Egypt election map blog post

### PR DESCRIPTION
**Pull request by davidheyman**
Blog post about some style effects used on the Egypt Election map.

### CODE REVIEW

**Comment by davidheyman** [comment]
@awoodruff @bcsheesley Can you guys read this and either commit any changes or merge it if it looks good?

**Comment by awoodruff** [comment]
Looks good to me! I'll merge unless @bcsheesley has any objections.

**Comment by bcsheesley** [comment]
Me too. Nice post! Please go ahead and merge away.

**Comment by davidheyman** [comment]
Published. Thanks!

**Pull request merged**
