### PR TITLE
Eshhad post and project

### PR DESCRIPTION
**Pull request by davidheyman**
This is worth a read and an edit while I quickly finish the portfolio item to go with it.

### CODE REVIEW

**Comment by davidheyman** [comment]
Especially from you @bcsheesley

**Comment by awoodruff** [comment]
This is awesome, for my two cents!

Since it comes up here, I've been wondering lately if there isn't a more public-friendly term for "data probe." It's a Harrowerian label that I don't really hear outside our cohort, and I worry a little bit that people don't know what it means at first glance.

Lastly, I noticed a couple of typos which I'll just go ahead and fix.

**Comment by davidheyman** [comment]
I know what you mean. The client-friendly term would be either _tooltip_ or _info window_. I think we could improve understanding if we changed it, but I want to be consistent across everything and there's _no way_ I could stop saying data probe now.

**Comment by bcsheesley** [comment]
Sorry, I need to check my email more often. The post looks great to me. I fixed a tiny typo, but made no other changes. 

Your four points nicely cover the main aspects of the design. "Color echoes" is a cool term... I think "use color sparingly" is my favorite section here, and I'm glad you put it first.

There are lots of images, which makes it a little long feeling, but maybe that's a good thing for people who don't want to go to the actual map. I wasn't sure how I felt about leading with an image from the NYT, though. I don't know if it's necessary, especially first thing. Can we do without it, yet keep your text and numbered list in tact? Also, I got temporarily lost looking at the Fixed Probe image, just because it shows the _entire_ UI. Not sure how you get around that, but maybe an arrow or something would tell people to look in the right place.

**Comment by bcsheesley** [comment]
Oh, one other thing, unrelated to the post itself. When I clicked the link to the map, I got this. I think the size of my browser window caused the filter buttons to be hidden by the Eshhad header:

eshhad_ _-_sectarian_attacks_in_egypt

**Comment by davidheyman** [comment]
Post and portfolio entry are deployed on the site

**Pull request merged**
